version: "3.5"

networks:
  bibbox-default-network:
    external: true




x-environment:
  &default-back-environment
  # Database settings
  POSTGRES_DB: taiga
  POSTGRES_USER: taiga
  POSTGRES_PASSWORD: taiga
  POSTGRES_HOST: taiga-db
  # Taiga settings
  TAIGA_SECRET_KEY: "taiga-back-secret-key"
  TAIGA_SITES_DOMAIN: "localhost:9000"
  TAIGA_SITES_SCHEME: "http"
  # Email settings. Uncomment following lines and configure your SMTP server
  # EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
  # DEFAULT_FROM_EMAIL: "no-reply@example.com"
  # EMAIL_USE_TLS: "False"
  # EMAIL_USE_SSL: "False"
  # EMAIL_HOST: "smtp.host.example.com"
  # EMAIL_PORT: 587
  # EMAIL_HOST_USER: "user"
  # EMAIL_HOST_PASSWORD: "password"
  # Rabbitmq settings
  # Should be the same as in taiga-async-rabbitmq and taiga-events-rabbitmq
  RABBITMQ_USER: taiga
  RABBITMQ_PASS: taiga
  # Telemetry settings
  ENABLE_TELEMETRY: "True"
  #SuperUser
  ADMIN_USER: admin
  ADMIN_EMAIL: admin@bibbox.org
  ADMIN_PASSWORD: vendetta
  
x-volumes:
  &default-back-volumes
  - ./data/taiga-static-data:/taiga-back/static
  - ./data/taiga-media-data:/taiga-back/media
  - ./data/create_admin.py:/taiga-back/create_admin.py
  # - ./config.py:/taiga-back/settings/config.py
  

services:
  bibbox-taiga-db:
    image: postgres:12.3
    container_name: bibbox-taiga-db
    environment:
      POSTGRES_DB: taiga
      POSTGRES_USER: taiga
      POSTGRES_PASSWORD: taiga
    volumes:
      - ./data/taiga-db-data:/var/lib/postgresql/data
    networks:
      - bibbox-default-network

  bibbox-taiga-back:
    image: taigaio/taiga-back:6.5.0
    container_name: bibbox-taiga-back
    environment: *default-back-environment
    volumes: *default-back-volumes
    networks:
      - bibbox-default-network
    depends_on:
      - bibbox-taiga-db
      - bibbox-taiga-events-rabbitmq
      - bibbox-taiga-async-rabbitmq
    links:
      - bibbox-taiga-db:taiga-db
      - bibbox-taiga-events-rabbitmq:taiga-events-rabbitmq
      - bibbox-taiga-async-rabbitmq:taiga-async-rabbitmq

  bibbox-taiga-create-admin:
    image: taigaio/taiga-back:6.5.0
    container_name: bibbox-taiga-create-admin
    environment: *default-back-environment
      
    depends_on:
      - bibbox-taiga-db
      - bibbox-taiga-back
      - bibbox-taiga-async
      - bibbox-taiga-events
      - bibbox-taiga-front
    links:
      - bibbox-taiga-db:taiga-db
      - bibbox-taiga-events-rabbitmq:taiga-events-rabbitmq
      - bibbox-taiga-async-rabbitmq:taiga-async-rabbitmq
    #entrypoint: "python create_admin.py"
    #entrypoint: "python manage.py createsuperuser --username=admin --email=admin@admin.com --noinput"
    #entrypoint: bash -c "printf 'admin\nadmin@bibbox.org\nvendetta\nvendetta\n' | python manage.py createsuperuser"
    entrypoint: bash -c "cat create_admin.py | python manage.py shell"
    volumes: *default-back-volumes
    networks:
      - bibbox-default-network
      
  bibbox-taiga-async:
    image: taigaio/taiga-back:6.5.0
    container_name: bibbox-taiga-async
    entrypoint: ["/taiga-back/docker/async_entrypoint.sh"]
    environment: *default-back-environment
    volumes: *default-back-volumes
    networks:
      - bibbox-default-network
    depends_on:
      - bibbox-taiga-db
      - bibbox-taiga-back
      - bibbox-taiga-async-rabbitmq
    links:
      - bibbox-taiga-db:taiga-db
      - bibbox-taiga-back:taiga-back
      - bibbox-taiga-async-rabbitmq:taiga-async-rabbitmq

  bibbox-taiga-async-rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: bibbox-taiga-async-rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: secret-erlang-cookie
      RABBITMQ_DEFAULT_USER: taiga
      RABBITMQ_DEFAULT_PASS: taiga
      RABBITMQ_DEFAULT_VHOST: taiga
    volumes:
      - ./data/taiga-async-rabbitmq-data:/var/lib/rabbitmq
    networks:
      - bibbox-default-network

  bibbox-taiga-front:
    image: taigaio/taiga-front:6.5.0
    container_name: bibbox-taiga-front
    environment:
      TAIGA_URL: "http://localhost:9000"
      TAIGA_WEBSOCKETS_URL: "ws://localhost:9000"
    networks:
      - bibbox-default-network
    # volumes:
    #   - ./conf.json:/usr/share/nginx/html/conf.json

  bibbox-taiga-events:
    image: taigaio/taiga-events:6.5.0
    container_name: bibbox-taiga-events
    environment:
      RABBITMQ_USER: taiga
      RABBITMQ_PASS: taiga
      TAIGA_SECRET_KEY: "taiga-back-secret-key"
    networks:
      - bibbox-default-network
    depends_on:
      - bibbox-taiga-events-rabbitmq
    links:
      - bibbox-taiga-events-rabbitmq:taiga-events-rabbitmq

  bibbox-taiga-events-rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: bibbox-taiga-events-rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: secret-erlang-cookie
      RABBITMQ_DEFAULT_USER: taiga
      RABBITMQ_DEFAULT_PASS: taiga
      RABBITMQ_DEFAULT_VHOST: taiga
    volumes:
      - ./data/taiga-events-rabbitmq-data:/var/lib/rabbitmq
    networks:
      - bibbox-default-network

  taiga-protected:
    image: taigaio/taiga-protected:6.5.0
    container_name: bibbox-taiga-protected
    environment:
      MAX_AGE: 360
      SECRET_KEY: "taiga-back-secret-key"
    networks:
      - bibbox-default-network

  bibbox-taiga-gateway:
    image: nginx:1.19-alpine
    container_name: bibbox-taiga-gateway
    ports:
      - "9000:80"
    volumes:
      - ./data/taiga-gateway/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data/taiga-gateway/proxy_params:/etc/nginx/proxy_params
      - ./data/taiga-static-data:/taiga/static
      - ./data/taiga-media-data:/taiga/media
    networks:
      - bibbox-default-network
    depends_on:
      - bibbox-taiga-front
      - bibbox-taiga-back
      - bibbox-taiga-events
    links:
      - bibbox-taiga-front:taiga-front
      - bibbox-taiga-back:taiga-back
      - bibbox-taiga-events:taiga-events
    



